lasdi:
  type: gplasdi
  gplasdi:
    # device: mps
    n_samples: 20
    lr: 0.001
    n_iter: 28000
    n_greedy: 2000
    max_greedy_iter: 28000
    sindy_weight: 0.1
    coef_weight: 1.e-6
    fd_type: sbp12
    path_checkpoint: checkpoint
    path_results: results

parameter_space:
  parameters:
    - name: a
      min: 0.7
      max: 0.9
      test_space_type: uniform
      sample_size: 21
      log_scale: false
    - name: w
      min: 0.9
      max: 1.1
      # another way of specifying test space.
      test_space_type: list
      list: [0.9, 0.91, 0.92, 0.93, 0.94,
             0.95, 0.96, 0.97, 0.98, 0.99,
             1.0, 1.01, 1.02, 1.03, 1.04,
             1.05, 1.06, 1.07, 1.08, 1.09, 1.1]
  test_space:
    type: grid

latent_space:
  type: ae
  ae:
  # we should not specify fom_dimension here. temporarily.
    fom_dimension: 1001
    hidden_units: [100]
    latent_dimension: 5

# TODO(kevin): temporary placeholder
initial_train:
  train_data: data/data_train.npy
  test_data: data/data_test.npy

physics:
  type: burgers1d
  burgers1d:
    number_of_timesteps: 1001
    simulation_time: 1.
    grid_size: [1001]
    xmin: -3.
    xmax: 3.
