name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  # docker-image:
  #   uses: ./.github/workflows/docker.yml
  api-doc:
    # needs: [docker-image]
    uses: ./.github/workflows/sphinx.yml