name: "Sphinx: Render docs"

# on: push
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/llnl/gplasdi/lasdi_env:latest
    #   options: --user 1001 --privileged
    #   volumes:
    #     - /mnt:/mnt
    permissions:
      contents: write
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html source build"
        pre-build-command: "pip install --upgrade pip && pip install sphinx-autoapi sphinx_rtd_theme"
      # run: |
      #     sphinx-build --version
      #     cd ${GITHUB_WORKSPACE}/docs
      #     mkdir build
      #     sphinx-build -b html source/ build/
    - name: check resulting files
      run: |
          ls ${GITHUB_WORKSPACE}/docs/build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      # if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build